# 동글 역할 명시 (필수)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# 스튜디오 기능 끄기 (빌드 에러 방지 필수)
CONFIG_ZMK_STUDIO=n

# 동글 화면 및 배터리 정보 수집 (필수)
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# RGB 에러 차단 (필수)
CONFIG_ZMK_RGB_UNDERGLOW=n